apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: {{ .Release.Name }}
  name: {{ include "opsgenie-exporter.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  endpoints:
    - interval: 10m
      targetPort: {{ .Values.service.port }}
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace | default "default" }}
  selector:
    matchLabels:
      {{- include "opsgenie-exporter.labels" . | nindent 6 }}